# Generated by Django 4.0.4 on 2022-05-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_sheet',
            field=models.TextField(default=''),
        ),
    ]
