# Generated by Django 4.0.4 on 2022-05-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_question_answer_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
