# Generated by Django 4.0.4 on 2022-05-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0006_alter_question_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
