# Generated by Django 4.0.4 on 2022-05-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0007_remove_question_test_delete_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='selection',
            new_name='votes',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_sheet',
            field=models.TextField(default=''),
        ),
    ]
