# Generated by Django 4.0.4 on 2022-05-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_rename_selection_choice_votes_question_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='selection',
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='qa.exam'),
        ),
    ]
