# Generated by Django 4.0.4 on 2022-05-28 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0009_exam_rename_votes_choice_selection_question_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='answer',
            new_name='votes',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='selection',
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qa.exam'),
        ),
    ]
