# Generated by Django 4.0.4 on 2022-05-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0012_rename_answer_question_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='score',
            field=models.IntegerField(default=100),
        ),
    ]
