# Generated by Django 4.0.4 on 2022-05-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0013_exam_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='num_of_question',
            field=models.IntegerField(default=0),
        ),
    ]
