# Generated by Django 4.0.4 on 2022-05-29 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0014_exam_num_of_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_sheet',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
